name: financebot
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python=3.*
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - beautifulsoup4
    - chardet
    - idna
    - lxml
    - requests
    - soupsieve
    - urllib3
#prefix: /home/bene/anaconda3/envs/financebot

